name: Publish images

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: dawidd6/action-docker-publish-changed@v1.0.0
        with:
          docker_username: ${{github.event.repository.owner.login}}
          docker_password: ${{secrets.PASS}}
          github_token: ${{secrets.GITHUB_TOKEN}}
